config/routes.rb
Rails.application.routes.draw do
  get '/gossips/:gossip_id/like/create', to: 'like#create'
  get '/gossips/:gossip_id/like/destroy', to: 'like#destroy'
  get '/comments/:comment_id/comment/new', to: 'comments#new', as: 'new_comment_comment'
  post '/comments/:comment_id/comments', to: 'comments#create', as: 'comment_comments' 
  get 'registration/new'
  get '/logout', to: 'registration#logout'
  get '/not_connected', to: 'static_pages#not_connected'
  get '/invalid_login_password', to: 'static_pages#invalid_login_password'
  post 'registration/create'
  root 'static_pages#home'
  resources :users, only: [:index, :new, :create]
  resources :gossips do
    resources :comments, except: [:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :content, :dependent => :destroy
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_and_belongs_to_many :tags
  belongs_to :user
  has_many :likes, as: :content, :dependent => :destroy
  has_many :comments, as: :commentable, :dependent => :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_and_belongs_to_many :recipients, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :likes
  has_many :comments
  has_many :sent_messages, class_name: "PrivateMessage", foreign_key: "sender_id"
  has_and_belongs_to_many :received_messages, class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  @@session = nil
  before_action :set_session

  def self.set_session(user)
    @@session = user
  end

  def self.get_session
    return @@session
  end

  def set_session
    @current_user = ApplicationController.get_session
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    unless @current_user
      redirect_to(not_connected_path)
    end
  end

  def create
    result = comment_params
    if params[:gossip_id]
      
      result[:commentable_type] = "Gossip"
      result[:commentable_id] = params[:gossip_id]
      comment = Comment.create(result)
      redirect_to(gossip_path(params[:gossip_id]))
    else
      result[:commentable_type] = "Comment"
      result[:commentable_id] = params[:comment_id]
      comment = Comment.create(result)
      redirect_to(gossip_path(Comment.find(params[:comment_id]).commentable_id))
    end
  end

  def edit
    unless @current_user
      redirect_to(not_connected_path)
    end
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to(gossip_path(params[:gossip_id]))
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to(gossip_path(params[:gossip_id]))
  end

  private

  def comment_params
    unless @current_user
      redirect_to(not_connected_path)
    end
    result = params.require(:comment).permit(:content)
    result[:user_id] = @current_user.id
    return result
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
    unless @current_user
      redirect_to(not_connected_path)
    end
  end

  def create
    gossip = Gossip.create(gossip_params)
    redirect_to(gossip_path(gossip.id))
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments.order(:created_at)
  end

  def edit
    @gossip = Gossip.find(params[:id])
    unless @current_user == @gossip.user 
      redirect_to(not_connected_path)
    end
  end

  def update
    gossip = Gossip.find(params[:id])
    gossip.update(gossip_params)
    redirect_to(gossip_path(gossip.id))
  end

  def index
    @gossips = Gossip.all
  end

  def destroy
    gossip = Gossip.find(params[:id])
    gossip.destroy
    redirect_to(gossips_path)
  end

  private

  def gossip_params
    result = params.require(:gossip).permit(:content)
    result[:user_id] = @current_user.id
    return result
  end


end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def create
    Like.create(user_id: @current_user.id, content_type: "Gossip", content_id: params[:gossip_id] )
    redirect_to(request.referer)
  end

  def destroy
    
    like = Like.where(user_id: @current_user.id, content_type: "Gossip",content_id: params[:gossip_id]).first
    like.destroy
    redirect_to(request.referer)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
  end

  def create
    @user_current = User.where(email: params[:email], password: params[:password]).first
    ApplicationController.set_session(@user_current)
    if @user_current
      redirect_to(gossips_path)
    else
      redirect_to(invalid_login_password_path)
    end
  end

  def logout
    ApplicationController.set_session(nil)
    redirect_to(root_path)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    puts "********home => current_user??************"
    puts @current_user
  end

  private

  def not_connected
  end

  def invalid_login_pasword
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:first_name, :email, :password, :city_id))
    redirect_to(root_path)
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Editer le commentaire </h1>
<%= form_for @comment, :url => gossip_comment_path do |f|%>
  <div class="form-group col-md-6">
    <label>Commentaire</label>  
    <%= f.text_area :content, size: "20x3", class: "form-control"%>
  </div>
  <div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary">Editer le commentaire</button>
  </div>
<%end%>

app/views/comments/new.html.erb
<h1>Création d'un commentaire</h1>
<%= form_for @comment, :url => gossip_comments_path do |f|%>
  <div class="form-group col-md-6">
    <label>Commentaire</label>  
    <%= f.text_area :content, size: "20x3", class: "form-control", placeholder: "Saisissez ici votre commentaire" %>
  </div>
  <div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary">Commenter</button>
  </div>
<%end%>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Editer un Gossip</h1>
<%= form_for @gossip do |f|%>
  <div class="form-group col-md-6">
    <label>Contenu du gossip</label>  
    <%= f.text_area :content, size: "20x3", class: "form-control" %>
  </div>
  <div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary">Editer le gossip</button>
  </div>
<%end%>

app/views/gossips/index.html.erb
<div class="d-flex"> 
  <h1>Index des gossips </h1>

<%= link_to 'Créer un gossip', new_gossip_path, class:"btn btn-success mx-4 align-self-center" %>
<br><br>
</div>

<div class="row">
  <% @gossips.each do |gossip| %>
    <div class="col-lg-3 d-flex align-items-stretch">
      <div class="card my-3">
        <div class="card-body">
          <div style="diplay: flex">
            <h5 class="card-title"> 
              Gossip numéro : <%= gossip.id %>  
            </h5>
          </div>
          <h6 class="card-subtitle mb-2 text-muted"> <strong>Auteur</strong> : <%=gossip.user.first_name%> (<%=gossip.user.email%>) </h6>
          <p class="card-text" > <strong>Contenu</strong>: <%= gossip.content %> </p>
        </div>
        <div class="row">
          <div class="col-lg-2">
            <%= link_to 'Détails', gossip_path(gossip.id), class:"btn btn-link" %>
          </div>
          <div class="col-lg-4">
          </div>
          <div class="col-lg-3">
            <p> 
              <%= gossip.comments.count %> 
              <%= image_tag("comment-png-17.png", :alt => "commentaires", :style => "width: 30px;") %>
            </p>
          </div>
          <div class="col-lg-3">
            <p> 
              <%= gossip.likes.count %> 
              <% if @current_user == nil%>
                <%= image_tag("Facebook-Like-grey.png", :alt => "likes", :style => "width: 30px;") %>
              <% elsif gossip.likes.where(user_id: @current_user.id).first%>
                <a href="/gossips/<%= gossip.id %>/like/destroy">
                  <%= image_tag("Facebook-Like.png", :alt => "likes", :style => "width: 30px;") %>
                </a>
              <% else%>
                <a href="/gossips/<%= gossip.id %>/like/create">
                  <%= image_tag("Facebook-Like-grey.png", :alt => "likes", :style => "width: 30px;") %>
                </a> 
              <% end %>

            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
  <h1>Création d'un Gossip</h1>
  <%= form_for @gossip do |f|%>
    <div class="form-group col-md-6">
      <label>Contenu du gossip</label>  
      <%= f.text_area :content, size: "20x3", class: "form-control", placeholder: "Saisissez ici votre texte" %>
    </div>
    <div class="form-group col-md-12">
      <button type="submit" class="btn btn-primary">Créer le gossip</button>
    </div>
  <%end%>

app/views/gossips/show.html.erb
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title"> Gossip numéro : <%= @gossip.id %>  </h5>
    <h6 class="card-subtitle mb-2 text-muted"> <strong>Auteur</strong> : <%=@gossip.user.first_name%> (<%=@gossip.user.email%>) </h6>
    <p class="card-text" > <strong>Contenu</strong> : <%= @gossip.content %> </p>
  </div>
  <div class="row">
    <div class="col-lg-6">
    </div>
    <div class="col-lg-3">
      <p> 
        <%= @gossip.comments.count %> 
        <%= image_tag("comment-png-17.png", :alt => "commentaires", :style => "width: 30px;") %>
      </p>
    </div>
    <div class="col-lg-3">
      <p> 
        <%= @gossip.likes.count %> 
        <% if @current_user == nil%>
          <%= image_tag("Facebook-Like-grey.png", :alt => "likes", :style => "width: 30px;") %>
        <% elsif @gossip.likes.where(user_id: @current_user.id).first%>
          <a href="/gossips/<%= @gossip.id %>/like/destroy">
            <%= image_tag("Facebook-Like.png", :alt => "likes", :style => "width: 30px;") %>
          </a>
        <% else%>
          <a href="/gossips/<%= @gossip.id %>/like/create">
            <%= image_tag("Facebook-Like-grey.png", :alt => "likes", :style => "width: 30px;") %>
          </a> 
        <% end %>

      </p>
    </div>
  </div>
</div>

<br>
<%= link_to 'Editer', edit_gossip_path(@gossip.id), class:"btn btn-outline-primary"%>
<%if @current_user == @gossip.user%>
  <%= link_to 'Détruire', @gossip, class:"btn btn-danger", data: {confirm: "êtes-vous sûr ?"}, method: :delete %>
<%end%>
<%= link_to "Retour à l'index", gossips_path, class:"btn btn-secondary"%>
<%= link_to "ajouter un commentaire", new_gossip_comment_path(@gossip.id), class:"btn btn-success"%>
<br>

<% @comments.each do |comment| %>
  <hr>
  <p>"<%=comment.content%>"</p>
  <p>
    <em>commenté par <%=comment.user.first_name%> (<%=comment.user.email%>)</em>

    <div class="row">
      <div class="col-lg-2">
        <%if @current_user == comment.user %>
          <%= link_to "éditer", edit_gossip_comment_path(@gossip.id, comment.id), class:"btn btn-link"%>
          <%= link_to 'Détruire', gossip_comment_path(@gossip.id, comment.id), class:"btn btn-danger", data: {confirm: "êtes-vous sûr ?"}, method: :delete %>
        <%end%>
      </div>
      <%if @current_user%>
        <% com_com = Comment.new %>
        <div class="col-lg-10">
          
          <%= form_for com_com, :url => comment_comments_path(comment.id) do |f|%>
            <div class="form-row">
              <div class="col">
                <%= f.text_field :content, class: "form-control", placeholder: "répondez au commentaire" %>
              </div>
              <div class="col">
                <button type="submit" class="btn btn-primary">Commenter</button>
              </div>
            </div>
          <%end%>
          
        </div>
      <%end%>
    </div>
  </p>

  <% comment.comments.each do |com_com| %>
    <hr>
    <div style="margin-left: 80px">
      <p>"<%=com_com.content%>"</p>
      <p>
        <em>commenté par <%=com_com.user.first_name%> (<%=com_com.user.email%>)</em>
      </p>
    </div>
  <%end%>
  

<%end%>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/like/create.html.erb
<h1>Like#create</h1>
<p>Find me in app/views/like/create.html.erb</p>

app/views/like/destroy.html.erb
<h1>Like#destroy</h1>
<p>Find me in app/views/like/destroy.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron text-center">
  <%if @current_user%>
    <h1>Bienvenue <%= @current_user.first_name%> !</h1>
  <%else%>
    <h1>Bienvenue !</h1>
  <%end%>
  <h3>
    Ici, tu peux retrouver des potins sur les moussaillons par les moussaillons 🎓
  </h3>
  <br>
  <%= link_to "Enregistre-toi !", new_user_path, class: "btn btn-lg btn-primary" %>
  <%unless @current_user%>
    <%= link_to "Connecte-toi !", registration_new_path, class: "btn btn-lg btn-link" %>
  <%end%>
</div>

app/views/static_pages/invalid_login_password.html.erb
<h1>Login et Mot de passe invalides! Veuillez recommencer.</h1>

app/views/static_pages/not_connected.html.erb
<h1>Veuillez vous connecter pour accéder à cette fonctionnalité...</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>

<div class="row">
  <% @gossips.each do |gossip| %>
    <div class="card col-lg-3" >
      <div class="card-body">
        <h5 class="card-title"> Gossip numéro : <%= gossip.id %>  </h5>
        <p> Nombre de commentaires : <%= gossip.comments.count %> </p>
        <h6 class="card-subtitle mb-2 text-muted"> Auteur : <%=gossip.anonymous_gossiper%> </h6>
        <p class="card-text" > Contenu: <%= gossip.content %> </p>
      </div>
      <%= link_to 'Détails', gossip_path(gossip.id), class:"btn btn-link" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<div class="row">
  <% @users.each do |user| %>
    <div class="card col-lg-3" >
      <div class="card-body">
        <h5 class="card-title"> User numéro : <%= user.id %>  </h5>
        <h6 class="card-subtitle mb-2 text-muted"> Prénom : <%=user.first_name%> </h6>
        <p class="card-text" > Email: <%= user.email %> </p>
        <p class="card-text" > MDP: <%= user.password %> </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Enregistrement d'un utilisateur</h1>

<%= form_for @user do |f|%>
  <div class="col-md-6">

    <div class="form-group">
      <label>First Name</label>  
      <%= f.text_field :first_name, class: "form-control", placeholder: "Jean" %>
    </div>

    <div class="form-group">
      <label>Ville</label>  
      <%= f.collection_select :city_id, City.order(:name),:id,:name, {include_blank: false}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <label>Email</label>  
      <%= f.text_field :email, class: "form-control", placeholder: "jean@email.com" %>
    </div>

    <div class="form-group">
      <label>Mot de passe</label>  
      <%= f.password_field :password, class: "form-control", placeholder: "*******" %>
    </div>
    
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Créer le compte</button>
    </div>
  </div>
<%end%>