config/routes.rb
Rails.application.routes.draw do
  get '/gossips/:gossip_id/like/create', to: 'like#create'
  get '/gossips/:gossip_id/like/destroy', to: 'like#destroy'
  get '/comments/:comment_id/comment/new', to: 'comments#new', as: 'new_comment_comment'
  post '/comments/:comment_id/comments', to: 'comments#create', as: 'comment_comments' 
  get 'registration/new'
  get '/logout', to: 'registration#logout'
  get '/not_connected', to: 'static_pages#not_connected'
  get '/invalid_login_password', to: 'static_pages#invalid_login_password'
  post 'registration/create'
  root 'static_pages#home'
  resources :users, only: [:index, :new, :create]
  resources :gossips do
    resources :comments, except: [:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :content, :dependent => :destroy
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_and_belongs_to_many :tags
  belongs_to :user
  has_many :likes, as: :content, :dependent => :destroy
  has_many :comments, as: :commentable, :dependent => :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_and_belongs_to_many :recipients, class_name: "User"

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :likes
  has_many :comments
  has_many :sent_messages, class_name: "PrivateMessage", foreign_key: "sender_id"
  has_and_belongs_to_many :received_messages, class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  @@session = nil
  before_action :set_session

  def self.set_session(user)
    @@session = user
  end

  def self.get_session
    return @@session
  end

  def set_session
    @current_user = ApplicationController.get_session
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    unless @current_user
      redirect_to(not_connected_path)
    end
  end

  def create
    result = comment_params
    if params[:gossip_id]
      
      result[:commentable_type] = "Gossip"
      result[:commentable_id] = params[:gossip_id]
      comment = Comment.create(result)
      redirect_to(gossip_path(params[:gossip_id]))
    else
      result[:commentable_type] = "Comment"
      result[:commentable_id] = params[:comment_id]
      comment = Comment.create(result)
      redirect_to(gossip_path(Comment.find(params[:comment_id]).commentable_id))
    end
  end

  def edit
    unless @current_user
      redirect_to(not_connected_path)
    end
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to(gossip_path(params[:gossip_id]))
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to(gossip_path(params[:gossip_id]))
  end

  private

  def comment_params
    unless @current_user
      redirect_to(not_connected_path)
    end
    result = params.require(:comment).permit(:content)
    result[:user_id] = @current_user.id
    return result
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
    unless @current_user
      redirect_to(not_connected_path)
    end
  end

  def create
    gossip = Gossip.create(gossip_params)
    redirect_to(gossip_path(gossip.id))
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments.order(:created_at)
  end

  def edit
    @gossip = Gossip.find(params[:id])
    unless @current_user == @gossip.user 
      redirect_to(not_connected_path)
    end
  end

  def update
    gossip = Gossip.find(params[:id])
    gossip.update(gossip_params)
    redirect_to(gossip_path(gossip.id))
  end

  def index
    @gossips = Gossip.all
  end

  def destroy
    gossip = Gossip.find(params[:id])
    gossip.destroy
    redirect_to(gossips_path)
  end

  private

  def gossip_params
    result = params.require(:gossip).permit(:content)
    result[:user_id] = @current_user.id
    return result
  end


end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def create
    Like.create(user_id: @current_user.id, content_type: "Gossip", content_id: params[:gossip_id] )
    redirect_to(request.referer)
  end

  def destroy
    
    like = Like.where(user_id: @current_user.id, content_type: "Gossip",content_id: params[:gossip_id]).first
    like.destroy
    redirect_to(request.referer)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:first_name, :email, :password, :city_id))
    redirect_to(root_path)
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/"><h3>GossipBook</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href = "<%= gossips_path %>" > Index des gossips <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href = "<%= new_gossip_path %>"> Nouveau gossip <span class="sr-only">(current)</span></a>
      </li>
        <a href = "<%= users_path %>"> ******** <span class="sr-only">(current)</span></a>
    </ul>
    <ul class="navbar-nav navbar-right">
      <% if @current_user%>
        <li class="nav-item active">
          <a class="nav-link">User: "<%= @current_user.first_name%>"</a>
        </li>
        <li class="nav-item active">
          <a href="/logout" class="nav-link">Déconnexion</a>
        </li>
      <%else%>
        <li class="nav-item active">
          <a href="/registration/new" class="nav-link">Me connecter</a>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
    <%= render "layouts/header" %>
    
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>